### PR TITLE
Add ms013g for offical support to ms013g

### PR DESCRIPTION
**Pull request by aditheking**
ms013g official support my RR build is stable

### CODE REVIEW

**Comment by akhilnarang** [comment]
no, make a pull request in settings repo :|, adding your name to teh list

**Comment by varund7726** [comment]
Not here . In settings https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/blob/marshmallow/res/values/resurrection_device_maintainers_strings.xml

**Comment by aditheking** [comment]
U mean settings apk ??

**Comment by aditheking** [comment]
ok i got

**Pull request closed without merging**
