### PR TITLE
Create ms013g.xml

### PR DESCRIPTION
**Pull request by aditheking**

### CODE REVIEW

**Comment by akhilnarang** [comment]
Fork the repo, and add it :)

**Comment by aditheking** [comment]
Can ms013g get official support i have compile rr latest v5.6.7 and its stable fully so can u add ms013g grand 2 SM-G7102

**Comment by akhilnarang** [comment]
make a pull request in settings for that, and talk to any of the team on hangouts

**Comment by aditheking** [comment]
i already talked to many shubhang westcrip bt no one replies it and see the msg

**Comment by aditheking** [comment]
Can i talk to u
my aupreti72@gmail.com

**Comment by aditheking** [comment]
I sent u and varun invite on hangouts plz join

**Comment by varund7726** [comment]
@aditheking didn't you see what akhil said? Merge a pull request

**Pull request closed without merging**
