### PR TITLE
ms013g ota

### PR DESCRIPTION
**Pull request by aditheking**
@varund7726 @akhilnarang  add this device im already maintainer for ms013g

### CODE REVIEW

**Comment by akhilnarang** [comment]
Fork the repo, or create one
host on your own github account account or anywhere else :)

**Comment by aditheking** [comment]
@akhilnarang see the device is added here also https://s.basketbuild.com/devs/resurrectionremix/ms013g

Please merge this pull request

**Comment by varund7726** [comment]
@aditheking what hes trying to say is this repo is for RR dev team only. you have to create your own repo on your github account and link the ota_cof file there

**Comment by aditheking** [comment]
@varund7726 OK I will do that but are u sure that ota updates will work I mean will users will get ota updates

**Comment by aditheking** [comment]
https://github.com/aditheking/OTA is this ok

**Comment by varund7726** [comment]
looks ok...send me a screenshot of OTA app

**Comment by aditheking** [comment]
@varund7726 [http://s31.postimg.org/w52uxoayz/Screenshot_20160423_153409.png](url)

**Comment by varund7726** [comment]
have you included ota_conf file in RR folder?

**Comment by aditheking** [comment]
Removed

**Comment by aditheking** [comment]
@varund7726 @akhilnarang https://github.com/aditheking/ResurrectionRemix_ms013g_OTA
https://github.com/aditheking/OTA is this correct now

**Comment by varund7726** [comment]
Are you understanding what I'm saying ? You need the ota_conf in RR folder and ota_conf must contain link of XML github

**Comment by aditheking** [comment]
Check ota conf I already added link to XML but still ota not working @varund7726

**Comment by varund7726** [comment]
But is ota_conf  in your RR folder?

**Comment by aditheking** [comment]
@varund7726 which RR folder

**Comment by akhilnarang** [comment]
you need to keep ota_conf file in the root of your RR source

**Comment by varund7726** [comment]
@aditheking sorry to say but you must have that much knowledge about this atleast to be a maintainer...if you dont , tell me

**Comment by owlseye** [comment]
Look:
This is a template file which you need to put into the source root (your source folder).
https://github.com/ResurrectionRemix/OTA/blob/master/altan ota_conf

Link your remote ota file there.

**Pull request closed without merging**
